spring.application.name=inundago-backend
server.port=8888

spring.datasource.url=jdbc:postgresql://localhost:5432/inundago
spring.datasource.username=postgres
spring.datasource.password=CAMBIAR
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=CAMBIAR
app.jwt.expiration-minutes=120

cors.allowed-origins=http://localhost:4200

mapbox.api.key=CAMBIAR

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

logging.level.root=ERROR
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE


